<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>PS5 PKG Tool</AssemblyName>
    <RootNamespace>PS5PKGTool</RootNamespace>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>PS5 PKG Tool</Product>
    <Company>pearlxcore</Company>
    <Copyright>Copyright (c) pearlxcore</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PS5PKGTool.Core\PS5PKGTool.Core.csproj" />
    <ProjectReference Include="..\PS5PKGTool.Ffpfsc\PS5PKGTool.Ffpfsc.csproj" />
    <ProjectReference Include="..\PS5PKGTool.Ufs2\PS5PKGTool.Ufs2.csproj" />
    <ProjectReference Include="..\..\DarkUI\DarkUI\DarkUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.png" />
    <EmbeddedResource Include="icon.ico">
      <LogicalName>PS5PKGTool.icon.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
